language: node_js
node_js:
  - '>= 8'
cache:
  directories:
    - node_modules
sudo: required
before_install:
  - google-chrome-stable --headless --no-sandbox
install:
  - yarn install
  - grunt eslint
